### ISSUE TITLE
Cannot read property * of undefined

### ISSUE THREAD

**Issue by bitnom** [jmccraw/videojs-suggestedVideoEndcap#1]
I'm getting a few errors when trying to use your script. I'm not sure how to fix it. Here's my page: https://goo.gl/MHpwJC

hope you can help

thanks

**Comment by bitnom** [comment]
script needs to be updated for recent versions of videojs. I had to use a very old version to get it to work.

**Comment by jmccraw** [comment]
Sorry for just seeing this. Updated to the latest version of VideoJS.
